/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'
import { Route as AccountsIdStatementRouteImport } from './routes/accounts.$id.statement'
import { Route as AccountsIdPassbookRouteImport } from './routes/accounts.$id.passbook'

const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsIdStatementRoute = AccountsIdStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => AccountsIdRoute,
} as any)
const AccountsIdPassbookRoute = AccountsIdPassbookRouteImport.update({
  id: '/passbook',
  path: '/passbook',
  getParentRoute: () => AccountsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/accounts/$id': typeof AccountsIdRouteWithChildren
  '/accounts/$id/passbook': typeof AccountsIdPassbookRoute
  '/accounts/$id/statement': typeof AccountsIdStatementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/accounts/$id': typeof AccountsIdRouteWithChildren
  '/accounts/$id/passbook': typeof AccountsIdPassbookRoute
  '/accounts/$id/statement': typeof AccountsIdStatementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/accounts/$id': typeof AccountsIdRouteWithChildren
  '/accounts/$id/passbook': typeof AccountsIdPassbookRoute
  '/accounts/$id/statement': typeof AccountsIdStatementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/accounts/$id'
    | '/accounts/$id/passbook'
    | '/accounts/$id/statement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/accounts/$id'
    | '/accounts/$id/passbook'
    | '/accounts/$id/statement'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/accounts/$id'
    | '/accounts/$id/passbook'
    | '/accounts/$id/statement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/$id/statement': {
      id: '/accounts/$id/statement'
      path: '/statement'
      fullPath: '/accounts/$id/statement'
      preLoaderRoute: typeof AccountsIdStatementRouteImport
      parentRoute: typeof AccountsIdRoute
    }
    '/accounts/$id/passbook': {
      id: '/accounts/$id/passbook'
      path: '/passbook'
      fullPath: '/accounts/$id/passbook'
      preLoaderRoute: typeof AccountsIdPassbookRouteImport
      parentRoute: typeof AccountsIdRoute
    }
  }
}

interface AccountsIdRouteChildren {
  AccountsIdPassbookRoute: typeof AccountsIdPassbookRoute
  AccountsIdStatementRoute: typeof AccountsIdStatementRoute
}

const AccountsIdRouteChildren: AccountsIdRouteChildren = {
  AccountsIdPassbookRoute: AccountsIdPassbookRoute,
  AccountsIdStatementRoute: AccountsIdStatementRoute,
}

const AccountsIdRouteWithChildren = AccountsIdRoute._addFileChildren(
  AccountsIdRouteChildren,
)

interface AccountsRouteChildren {
  AccountsIdRoute: typeof AccountsIdRouteWithChildren
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsIdRoute: AccountsIdRouteWithChildren,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
